name: Auto News Build Schedule
on:
  schedule:
    - cron: '0 */3 * * *' # Awtomatikong mag-rebuild kada 3 oras (e.g., 12AM, 3AM, 6AM, 9AM...)
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
